### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by wahid18benz** [daya6489/SmartEDA#1]
Great job!

Can you provide the documentation of the package, I mean each class with functions and their parameters ?! 

Thank you,

**Comment by sayanddude** [comment]
@wahid18benz Hi! You can find the detailed documentation of the package here- https://cran.r-project.org/web/packages/SmartEDA/SmartEDA.pdf

Also, if you are using SmartEDA in any of your project/work/research, then please cite our paper - https://joss.theoj.org/papers/10.21105/joss.01509
