### ISSUE TITLE
SmartEDA does not seem to adhere to set factor levels when plotting & graphs factors alphabetically

### ISSUE THREAD

**Issue by SugarRayLua** [daya6489/SmartEDA#11]
Dear Developers,
I really like the functionality of the SmartEDA package. However, one stumbling block for me to use it in my workflow is that the functions ExpNumViz and ExpCatViz do not seem to adhere to the factor levels that I set and instead graph my factors alphabetically as if I never set my factor levels which doesn't allow me to share the results of those functions effectively with colleagues. 

I've attached a screen shot of the issue using an example from the mtcars dataset. 

Thanks!

![IMG_1279](https://user-images.githubusercontent.com/76857619/234403574-b860fa0b-30b5-43cc-8277-9c29528bc5db.jpeg)

**Comment by daya6489** [comment]
this issues has been fixed in the latest version 0.3.10. thanks for raising up this issues.
![image](https://github.com/daya6489/SmartEDA/assets/17849762/341a46b3-914c-4f2a-83ca-3bc51133d634)

**Comment by SugarRayLua** [comment]
Thank you! 😊
