### ISSUE TITLE
error Centos 7 MRO 3.5.2

### ISSUE THREAD

**Issue by pfv07** [daya6489/SmartEDA#3]
Hi, i try to install the package and have the next error:

install.packages("SmartEDA",repos="http://cran.cnr.berkeley.edu/",type="source")

* installing *source* package ‘SmartEDA’ ...
** package ‘SmartEDA’ successfully unpacked and MD5 sums checked
** R
** inst
** byte-compile and prepare package for lazy loading
Error : object ‘hcl.colors’ is not exported by 'namespace:grDevices'
ERROR: lazy loading failed for package ‘SmartEDA’

**Comment by daya6489** [comment]
the problem is, there is a R package called grDevices, it should be up to dated. The older version of the grDevice does'nt have hcl.colors function.

**Comment by daya6489** [comment]
grDevice is the inbuilt package developed by R cran core team. And to update grDevice you have to update your R software latest version

**Comment by pfv07** [comment]
I can't do that, because I using MRO and need the MKL libraries and multi core 
If you have a work-around let me know ...
tks

**Comment by daya6489** [comment]
Sure. I will make that change in next version of the SmartEDA package.

**Comment by daya6489** [comment]
The changes had done on git version. You can install the SmartEDA using git repo
devtools::install_github("daya6489/SmartEDA",ref = "master")
