### ISSUE TITLE
ExpOutliers function is not working . May I know the reason why!

### ISSUE THREAD

**Issue by Vaishnavikumara** [daya6489/SmartEDA#4]
HI , I am trying to test the outlier detection function in SmartEDA package . But I am getting the following error 
 **ExpOutliers(trees, varlist = c("Girth","Weight","Height"), method = 'BoxPlot',capping = c(0.1, 0.9), outflag = TRUE)
Error in ExpOutliers(trees, varlist = c("Girth", "Weight", "Height"),  : 
  could not find function "ExpOutliers"**

Please help!

**Comment by daya6489** [comment]
Did you called SmartEDA library before that lines of code?
Can you check the below code
library('SmartEDA')
ExpOutliers(mtcars, varlist = c("mpg","disp","wt", "qsec"), method = 'BoxPlot', capping = c(0.1, 0.9), outflag = TRUE)
Please let me know if you are still facing the issues

**Comment by Vaishnavikumara** [comment]
Yeah. I called the library . To cross check I tested the ExpOutQQ function and it did work . I am only facing the issue with ExpOutliers function

**Comment by daya6489** [comment]
have you faced any issues while installing the SmartEDA package like hcl.colors not extracted from grDEvices something?

**Comment by daya6489** [comment]
Also can you check what is the R version you are using 'sessinInfo()'. There is R inbuilt package called grDevice, and it has function named hcl.colours only available in R version 3.6.0 and above. If your R version is lesser than that could you please update your R software with the latest version and install SmartEDA. It will work

**Comment by Vaishnavikumara** [comment]
I have not faced any issue while installing SmartEDA . And my R version is 3.6.1. So , it should work no? But it is not.:(

**Comment by Vaishnavikumara** [comment]
Hey. It did work. I just restarted the session.Thanks for the help!

**Comment by daya6489** [comment]
No problem. Thank you for using the package. And let us know if need any improvement on the function?

**Comment by Vaishnavikumara** [comment]
sure.Thanks!
