### ISSUE TITLE
Problem with date format

### ISSUE THREAD

**Issue by tlilburn** [daya6489/SmartEDA#5]
I have a data set in a tibble format. It contains dates, which are correctly formatted (as far as I can tell) as dttm and date values. When I run ExpData, I get the following message:
Error in as.POSIXlt.character(x, tz, ...) : 
  character string is not in a standard unambiguous format
What is smartEDA looking for in terms of dates?
Thank you

**Comment by daya6489** [comment]
There was an issue with ExpData function for Date format variable. Please try with the Latest version of SmartEDA_0.3.6 R package. The bugs are fixed in latest version.
