### ISSUE TITLE
Issue with ExpData when dealing with text data and tibbles

### ISSUE THREAD

**Issue by sausagesky** [daya6489/SmartEDA#8]
#So there is an issue with ExpData when dealing with tibbles and text data
# i have written this comment in Rscript format so that it can be replicated, as i cannot upload an rscript file
library(tidyverse)
library(SmartEDA)

# Using the data set enclosed, if we read in as a normal data.frame
mytest <- read.csv("aac_intakes_outcomes3.csv")
ExpData(mytest, 1)
#The bottom two lines of the output correctly read:
#12 %. of variables having >=50% and <90% missing cases 25% (1)
#13          %. of variables having >=90% missing cases  0% (0)
#
# We can confirm this with the report
ExpData(mytest, 2)

# if however, we read in as a tibble, we get
mytest2 <- read_csv("aac_intakes_outcomes3.csv")
ExpData(mytest2, 1)
#12 %. of variables having >=50% and <90% missing cases  0% (0)
#13          %. of variables having >=90% missing cases 25% (1)
#
# We also get the same type 2 report as before
ExpData(mytest2, 2)

# This can fix the problem with
mytest3 <- read_csv("aac_intakes_outcomes3.csv", na = " ")
ExpData(mytest3, 1)
ExpData(mytest3, 2)
#however, this fix is not great.
rm(list = ls())

[aac_intakes_outcomes3.csv](https://github.com/daya6489/SmartEDA/files/9586492/aac_intakes_outcomes3.csv)

**Comment by daya6489** [comment]
Thank you @sausagesky for these issues, we have fixed issues in the updated version 0.3.9
