### ISSUE TITLE
Minor spelling mistake 

### ISSUE THREAD

**Issue by bvittrant** [daya6489/SmartEDA#9]
Hi team,

Pure esthetic comment ^^

On this page : https://daya6489.github.io/SmartEDA/

_"An article describing SmartEDA pacakge for exploratory data analysis approach has been published in [arxiv](https://arxiv.org/pdf/1903.04754.pdf) and Journal of Open Source Software [JOSS](https://joss.theoj.org/papers/10.21105/joss.01509). Please cite the paper if you use SmartEDA in your work!"_

You mispelled _pacakge_ !

That's all. Have a nice day :)

**Comment by daya6489** [comment]
this has been fixed in the latest version. Thank you for raising this.
